# Generated by Django 2.2.7 on 2019-11-06 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0024_auto_20190906_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={},
        ),
        migrations.AddField(
            model_name='entity_relation_trait',
            name='entity_relation_type_trait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='context.Entity_Relation_Type_Trait'),
        ),
    ]
