# Generated by Django 3.1.4 on 2020-12-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0026_auto_20191205_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='details_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity_relation',
            name='details_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity_relation_trait',
            name='value_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity_trait',
            name='value_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term_relation',
            name='details_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
